repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-yaml
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.2.0
    hooks:
      - id: sign-commit
  - repo: .
    rev: v1.1.9
    hooks:
      - id: search-and-replace
